spring:
#  jackson:
#    serialization:
#      FAIL_ON_EMPTY_BEANS: false
  profiles: local
  autoconfigure:
    exclude:
      - org.redisson.spring.starter.RedissonAutoConfiguration
      - org.springframework.boot.autoconfigure.data.redis.RedisAutoConfiguration
  datasource:
    url: "jdbc:mysql://localhost/pfspring_web_app?useUnicode=yes&characterEncoding=UTF-8&characterSetResults=UTF-8&createDatabaseIfNotExist=true"
    username: 'root'
    password: ''
  jpa:
    properties:
      hibernate:
        cache:
          use_query_cache: false
          use_second_level_cache: false
          factory_class: org.redisson.hibernate.RedissonRegionFactory
#          redisson:
#            fallback: true
#            config: redission/redisson-dev.yaml
    show-sql: true
    hibernate:
      ddl-auto: update
  redis:
    host: localhost
    port: 6379
  cache:
    redis:
      key-prefix: dev_
      use-key-prefix: true
    type: none


management:
  health:
    elasticsearch:
      enabled: false