server:
  port: 9901
  error:
    path: "/error"
  compression:
    enabled: true
    min-response-size: 256
    mime-types: application/json,application/xml,text/html,text/xml,text/plain


spring:
  profiles:
    active: local
  datasource:
    url: 'jdbc:h2:mem:sq-quick-start'
    username: 'sa'
    password: ''

logging:
  pattern:
    console: '%clr(%d{yy-MM-dd E HH:mm:ss.SSS}){blue} %clr(%-5p) %clr(:){red} %clr(%m){faint}%n'
