spring:
  profiles: local
  datasource:
    url: 'jdbc:h2:mem:sq-quick-start'
    username: 'sa'
    password: ''

  redis:
    host: localhost
    port: 6379
  cache:
    redis:
      key-prefix: dev_